### PR TITLE
fix: harden native tx_preimage against missing non-signing scripts/amounts (#187)

### LINKED ISSUE #187: tx_preimage (native path) crashes when non-signing inputs lack locking_script — regression vs 2.2.x
## Summary

Since the native (`_bsv_native`) code path was introduced, `Transaction.preimage(i)` crashes with `AttributeError: 'NoneType' object has no attribute 'serialize'` when **any other input** of the transaction has `locking_script=None` — even though BIP143 does not use non-signing inputs' locking scripts at all.

This is a behavioral regression from the 2.2.x pure-Python path, which only read the locking script of the input being signed. Code that worked on 2.2.x (e.g. parse a tx with `Transaction.from_hex()`, restore the locking script for just the one input you want to verify, then call `preimage(i)`) now crashes on ≥2.3.0 whenever the native extension is available.

Still present on `v2.3.2` and current `master`.

## Reproduction

```python
from bsv import Transaction, P2PKH

# any multi-input tx parsed from raw hex — all inputs have locking_script=None
tx = Transaction.from_hex(raw_hex)

# restore source data only for the input we want the preimage of
tx.inputs[0].locking_script = P2PKH().lock(some_address)
tx.inputs[0].satoshis = 1000

tx.preimage(0)
# 2.2.x (pure Python): OK
# >=2.3.0 with _bsv_native: AttributeError: 'NoneType' object has no attribute 'serialize'
```

Traceback:

```
File "bsv/transaction.py", line 124, in preimage
    return tx_preimage(index, self.inputs, self.outputs, self.version, self.locktime)
File "bsv/transaction_preimage.py", line 245, in tx_preimage
    tx_version, tx_locktime, _inputs_to_tuples(inputs), _outputs_to_bytes(outputs)
File "bsv/transaction_preimage.py", line 69, in <listcomp>
    inp.locking_script.serialize(),
AttributeError: 'NoneType' object has no attribute 'serialize'
```

## Analysis

`_inputs_to_tuples()` serializes **all** inputs unconditionally ([`bsv/transaction_preimage.py` L64-75](https://github.com/bsv-blockchain/py-sdk/blob/v2.3.2/bsv/transaction_preimage.py#L64-L75)):

```python
def _inputs_to_tuples(inputs: list[TransactionInput]) -> list[tuple]:
    return [
        (
            inp.source_txid,
            inp.source_output_index,
            inp.locking_script.serialize(),   # <-- no None guard
            inp.satoshis or 0,                # <-- satoshis IS guarded
            inp.sequence,
            int(inp.sighash),
        )
        for inp in inputs
    ]
```

Note the inconsistency: `satoshis` is already defensively guarded with `or 0`, but `locking_script` is not.

The same file/repo already handles this correctly elsewhere:

- `bsv/transaction.py` L174 (`_calc_input_preimage_bip143_native`): `script = inp.locking_script.serialize() if inp.locking_script else b""`
- `_otda_serialize_input` (`transaction_preimage.py` ~L127-138) only serializes the locking script of the signing input and writes a varint 0 for all others.

Semantically, the guard is safe: in the BIP143 sighash algorithm the preimage of input *i* commits to the other inputs only via `hashPrevouts` (outpoints) and `hashSequence` — their locking scripts and amounts never enter the digest. So substituting `b""` for a missing non-signing locking script cannot change the result. (If the *signing* input itself lacks its script, the digest would be wrong with or without the guard — that remains the caller's responsibility, as in 2.2.x.)

## Suggested fix

```diff
 def _inputs_to_tuples(inputs: list[TransactionInput]) -> list[tuple]:
     return [
         (
             inp.source_txid,
             inp.source_output_index,
-            inp.locking_script.serialize(),
+            inp.locking_script.serialize() if inp.locking_script else b"",
             inp.satoshis or 0,
             inp.sequence,
             int(inp.sighash),
         )
         for inp in inputs
     ]
```

This restores parity with the 2.2.x pure-Python behavior and with the existing guard in `transaction.py` L174.

## Environment

- bsv-sdk v2.3.0 / v2.3.2 (also reproduced reading current `master`), built with the native extension (`BSV_REQUIRE_NATIVE=1`)
- Python 3.11 / 3.13

### PR DESCRIPTION
**Pull request by ALiberalVoluntarist**
## Summary

Fixes #187 (found via Ordinalx test feedback) plus an adjacent output-side sibling on the same native (`_bsv_native`) preimage path.

Since the native path was introduced, `Transaction.preimage(i)` crashed with
`AttributeError: 'NoneType' object has no attribute 'serialize'` whenever **another**
input of the transaction had `locking_script=None` — e.g. a tx parsed from raw hex
with only the signing input's prev-output restored. This is a regression vs the
2.2.x pure-Python path, which only reads the **signing** input's locking script.

## Input side (#187)

`_inputs_to_tuples()` serialized **all** inputs' locking scripts unconditionally.
The issue's suggested blanket `... if inp.locking_script else b""` guard fixes the
crash, but it also substitutes `b""` for the **signing** input, producing a digest
over an empty scriptCode — diverging from the pure-Python path (which requires the
signing input's script) and emitting garbage signatures. This was observed breaking
`test_unlocking_script_length_estimate_vs_actual_set_and_remove`: the KVStore
PushDrop unlocker relied on the crash to skip inputs whose source it hadn't linked,
and the blanket guard turned those skips into 2-byte empty-signature spends.

The fix, `_inputs_to_tuples_for_input(inputs, signing_index)` (used by the
single-input `tx_preimage` for BIP143 + OTDA, and by `_calc_input_preimage_bip143_native`):

- a **non-signing** input's missing script → `b""` (it never enters input *i*'s
  digest; it contributes only outpoints via `hashPrevouts` and sequences via
  `hashSequence`);
- the **signing** input's script is still required and raises when absent, matching
  the pure-Python `_preimage` / `_build_bip143_preimage`.

Verified against the **ts-sdk** (`TransactionSignature.format` — `otherInputs` read
only outpoints/sequences) and **go-sdk** (`CalcInputPreimage` — only the signing
input's `SourceTxScript()` is serialized) BIP143 implementations, both of which
never read a non-signing input's script.

## Output side (sibling)

The native path also serialized **all** outputs eagerly, crashing on an unfunded
output (`satoshis=None`) even when the signing input's sighash does not commit to it
(`SIGHASH_NONE`, or a non-target output under `SIGHASH_SINGLE`) — whereas the
pure-Python path skips it. `_outputs_to_bytes_for_input()` now serializes only the
committed outputs strictly and defensively zero-fills a **non-committed** unfunded
amount. A **committed** missing amount still raises on both paths (fail-fast — no
silently-wrong `SIGHASH_ALL` signature over amount 0).

> Note: ts-sdk/go-sdk default every output amount to 0 (`satoshis ?? 0` / uint64
> zero value) rather than erroring, but that is a type-system artifact, not a
> deliberate "sign unfunded outputs" semantic. For every real (funded) transaction
> all three SDKs produce byte-identical digests; this PR keeps py-sdk's fail-fast
> safety for the pathological committed-unfunded case.

## Safety / parity

Both changes are **no-ops for every funded, restored transaction** — the native path
stays byte-identical to the pure-Python path — and only alter the previously-crashing
edge cases. The C extension is unaffected: outputs cross the boundary as
pre-serialized bytes and inputs as `(…, script_bytes, …)` tuples, so all `None`
handling is necessarily at the Python layer; `parse_input_tuple` already accepts
empty script bytes cleanly.

## Tests

Adds 25 regression tests in `tests/bsv/native/test_equivalence.py` covering BIP143
and OTDA routing for:

- unrestored **non-signing** input → native preimage == pure-Python preimage;
- unrestored **signing** input → both paths raise (parity, prevents garbage sigs);
- unfunded output, **committed vs non-committed** position → outcomes agree on both paths.

Full non-live suite: **3440 passed, 46 skipped**. `ruff` + `black` clean. The
previously-failing KVStore E2E test now passes.

Fixes #187.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by ken16310 — APPROVED** [review]
ok
