### ISSUE TITLE
tx_preimage (native path) crashes when non-signing inputs lack locking_script — regression vs 2.2.x

### ISSUE THREAD

**Issue by ALiberalVoluntarist** [bsv-blockchain/py-sdk#187]
## Summary

Since the native (`_bsv_native`) code path was introduced, `Transaction.preimage(i)` crashes with `AttributeError: 'NoneType' object has no attribute 'serialize'` when **any other input** of the transaction has `locking_script=None` — even though BIP143 does not use non-signing inputs' locking scripts at all.

This is a behavioral regression from the 2.2.x pure-Python path, which only read the locking script of the input being signed. Code that worked on 2.2.x (e.g. parse a tx with `Transaction.from_hex()`, restore the locking script for just the one input you want to verify, then call `preimage(i)`) now crashes on ≥2.3.0 whenever the native extension is available.

Still present on `v2.3.2` and current `master`.

## Reproduction

```python
from bsv import Transaction, P2PKH

# any multi-input tx parsed from raw hex — all inputs have locking_script=None
tx = Transaction.from_hex(raw_hex)

# restore source data only for the input we want the preimage of
tx.inputs[0].locking_script = P2PKH().lock(some_address)
tx.inputs[0].satoshis = 1000

tx.preimage(0)
# 2.2.x (pure Python): OK
# >=2.3.0 with _bsv_native: AttributeError: 'NoneType' object has no attribute 'serialize'
```

Traceback:

```
File "bsv/transaction.py", line 124, in preimage
    return tx_preimage(index, self.inputs, self.outputs, self.version, self.locktime)
File "bsv/transaction_preimage.py", line 245, in tx_preimage
    tx_version, tx_locktime, _inputs_to_tuples(inputs), _outputs_to_bytes(outputs)
File "bsv/transaction_preimage.py", line 69, in <listcomp>
    inp.locking_script.serialize(),
AttributeError: 'NoneType' object has no attribute 'serialize'
```

## Analysis

`_inputs_to_tuples()` serializes **all** inputs unconditionally ([`bsv/transaction_preimage.py` L64-75](https://github.com/bsv-blockchain/py-sdk/blob/v2.3.2/bsv/transaction_preimage.py#L64-L75)):

```python
def _inputs_to_tuples(inputs: list[TransactionInput]) -> list[tuple]:
    return [
        (
            inp.source_txid,
            inp.source_output_index,
            inp.locking_script.serialize(),   # <-- no None guard
            inp.satoshis or 0,                # <-- satoshis IS guarded
            inp.sequence,
            int(inp.sighash),
        )
        for inp in inputs
    ]
```

Note the inconsistency: `satoshis` is already defensively guarded with `or 0`, but `locking_script` is not.

The same file/repo already handles this correctly elsewhere:

- `bsv/transaction.py` L174 (`_calc_input_preimage_bip143_native`): `script = inp.locking_script.serialize() if inp.locking_script else b""`
- `_otda_serialize_input` (`transaction_preimage.py` ~L127-138) only serializes the locking script of the signing input and writes a varint 0 for all others.

Semantically, the guard is safe: in the BIP143 sighash algorithm the preimage of input *i* commits to the other inputs only via `hashPrevouts` (outpoints) and `hashSequence` — their locking scripts and amounts never enter the digest. So substituting `b""` for a missing non-signing locking script cannot change the result. (If the *signing* input itself lacks its script, the digest would be wrong with or without the guard — that remains the caller's responsibility, as in 2.2.x.)

## Suggested fix

```diff
 def _inputs_to_tuples(inputs: list[TransactionInput]) -> list[tuple]:
     return [
         (
             inp.source_txid,
             inp.source_output_index,
-            inp.locking_script.serialize(),
+            inp.locking_script.serialize() if inp.locking_script else b"",
             inp.satoshis or 0,
             inp.sequence,
             int(inp.sighash),
         )
         for inp in inputs
     ]
```

This restores parity with the 2.2.x pure-Python behavior and with the existing guard in `transaction.py` L174.

## Environment

- bsv-sdk v2.3.0 / v2.3.2 (also reproduced reading current `master`), built with the native extension (`BSV_REQUIRE_NATIVE=1`)
- Python 3.11 / 3.13
